### ISSUE TITLE
Delete keys that starts with X

### ISSUE THREAD

**Issue by taliptako** [frideosapps/frideos_kvprx#1]
It woul be good if you can add support to delete all keys start with specific prefix

**Comment by frideosapps** [comment]
Hello @taliptako, feature added with the new version 0.2.0. Give a look at the method `bulkDeleteKeysStartWith`  on the Readme.md.

**Comment by taliptako** [comment]
Hi, probably this is the only package that let you specify a table for key-value storage thank you so much for this good work :)
